@php
    if(!isset($search)){
      $search=[];
    }
$bank=["Abhyudaya Co-Op Bank Ltd",
"Abu Dhabi Commercial Bank",
"Ahmedabad Mercantile Co-Op Bank Ltd",
"Allahabad Bank",
"Almora Urban Co-Operative Bank Ltd",
"Andhra Bank",
"Andhra Pragathi Grameena Bank",
"Apna Sahakari Bank Ltd",
"Austarlia and New Zealand Banking Gorup Ltd",
"Axis Bank",
"Bank Internasional Indonesia",
"Bank Of America",
"Bank Of Bahrain And Kuwait",
"Bank Of Baroda",
"Bank Of Ceylon",
"Bank Of India",
"Bank Of Maharashtra",
"Bank Of Nova Scotia",
"Bank Of Tokyo-Mitsubishi Ufj Ltd",
"Barclays Bank Plc",
"Bassein Catholic Co-Op Bank Ltd",
"Bharat Co-Op Bank (Mumbai) Ltd",
"Bnp Paribas",
"Canara Bank",
"Capital Local Area Bank Ltd",
"Catholic Syrian Bank Ltd",
"Central Bank Of India",
"Chinatrust Commercial Bank",
"Citibank",
"Citizencredit Co-Op Bank Ltd",
"City Union Bank Ltd",
"Commonwealth Bank of Australia",
"Corporation Bank",
"Cosmos Co-Op Bank Ltd",
"Credit Agricole Corp and Investment Bank",
"Credit Suisse Ag",
"Dbs Bank Ltd",
"Dena Bank",
"Deutsche Bank Ag",
"Development Credit Bank Ltd",
"Dhanlaxmi Bank Ltd",
"Dicgc",
"Dombivli Nagari Sahakari Bank Ltd",
"Federal Bank Ltd",
"Firstrand Bank Ltd",
"Greater Bombay Co-Op Bank Ltd",
"Gurgaon Gramin Bank",
"Hdfc Bank Ltd",
"Hsbc",
"Icici Bank Ltd",
"Idbi Bank Ltd",
"Indian Bank",
"Indian Overseas Bank",
"Indusind Bank Ltd",
"Ing Vysya Bank Ltd",
"Jalgaon Janata Sahkari Bank Ltd",
"Jammu And Kashmir Bank Ltd",
"Janakalyan Sahakari Bank Ltd",
"Janaseva Sahakari Bank Ltd Pune",
"Janata Sahkari Bank Ltd Pune",
"Jpmorgan Chase Bank",
"Kallappanna Awade Ich Janata S Bank",
"Kalupur Commercial Co Op Bank Ltd",
"Kalyan Janata Sahakari Bank Ltd",
"Kapole Co-Op Bank",
"Karnataka Bank Ltd",
"Karnataka State Co-Op Apex Bank Ltd",
"Karnataka Vikas Grameena Bank",
"Karur Vysya Bank",
"Kotak Mahindra Bank",
"Kurmanchal Nagar Sahakari Bank Ltd",
"Lakshmi Vilas Bank Ltd",
"Mahanagar Co-Op Bank Ltd",
"Maharashtra State Co-Op Bank",
"Mashreq Bank Psc",
"Mehsana Urban Co-Op Bank Ltd",
"Mizuho Corporate Bank Ltd",
"Mumbai District Central Co-Op Bank Ltd",
"Nagpur Nagarik Sahakari Bank Ltd",
"Nainital Bank Ltd",
"National Australia Bank",
"New India Co-Op Bank Ltd",
"Nkgsb Co-Op Bank Ltd",
"North Malabar Gramin Bank",
"Nutan Nagarik Sahakari Bank Ltd",
"Oman International Bank Saog",
"Oriental Bank Of Commerce",
"Parsik Janata Sahakari Bank Ltd",
"Prathama Bank",
"Prime Co-Operative Bank Ltd",
"Punjab And Maharashtra Co-Op Bank Ltd",
"Punjab And Sind Bank",
"Punjab National Bank",
"Rabobank International (CCRB)",
"Rajkot Nagarik Sahakari Bank Ltd",
"Ratnakar Bank Ltd",
"Reserve Bank Of India",
"Royal Bank Of Scotland",
"Saraswat Co-Op Bank Ltd",
"SBER Bank",
"Shamrao Vithal Co-Op Bank Ltd",
"Shinhan Bank",
"Shri Chhatrapati Rajarshi Shahu Urban Co-Op Bank Ltd",
"Societe Generale",
"South Indian Bank",
"Standard Chartered Bank",
"State Bank Of Bikaner And Jaipur",
"State Bank Of Hyderabad",
"State Bank Of India",
"State Bank Of Mauritius Ltd",
"State Bank Of Mysore",
"State Bank Of Patiala",
"State Bank Of Travancore",
"Sumitomo Mitsui Banking Corporation",
"Surat Peoples Co-Op Bank Ltd",
"Syndicate Bank",
"Tamilnad Mercantile Bank Ltd",
"Tamilnadu State Apex Co-Op Bank Ltd",
"Thane Bharat Sahakari Bank Ltd",
"Thane District Central Co-operative Bank Ltd",
"Thane Janata Sahakari Bank Ltd",
"The A.P. Mahesh Co-Op Urban Bank Ltd",
"The Akola District Central Co-operative Bank",
"The Gadchiroli District Central Co-operative Bank Ltd",
"The Gujarat State Co-Operative Bank Ltd",
"The Jalgaon Peoples Co-op Bank",
"The Kangra Co-Operative Bank Ltd.",
"The Karad Urban Co-Op Bank Ltd",
"The Municipal Co-Operative Bank Ltd. Mumbai",
"The Nasik Merchants Co-Op Bank Ltd",
"The Rajasthan State Co-Operative Bank Ltd",
"The Sahebrao Deshmukh Co-op Bank Ltd.",
"The Seva Vikas Co-operative Bank Ltd",
"The Surat District Co-Operative Bank Ltd",
"The Sutex Co Op Bank Ltd",
"The Varachha Co-Op. Bank Ltd",
"The Vishweshwar Sahakari Bank Ltd Pune",
"Tumkur Grain Merchants Cooperative Bank Ltd",
"UBS AG",
"Uco Bank",
"Union Bank Of India",
"United Bank Of India",
"Vasai Vikas Sahakari Bank Ltd",
"Vijaya Bank",
"West Bengal State Co-Op Bank Ltd",
"Westpac Banking Corporation",
"Woori Bank",
"Yes Bank Ltd",
"Other Bank"]
@endphp

<select @if(isset($id)) id="{{$id}}" @else id="bank" @endif @if(isset($class)) class="{{$class}}" @else class="form-control input-sm" @endif
@if(isset($required)){{$required}}@endif @if(isset($name)) name="{{$name}}" @else name="bank" @endif >
    <option value="">---Select---</option>
    @foreach($bank as $bankname)
        <option value="{{$bankname}}" @if(isset($selectid)&&($bankname==$selectid)) selected @endif>{{$bankname}}</option>
    @endforeach
</select>
