<?php

namespace App\Http\Controllers\MasterAdmin\Communication\MasterSetting;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AutoGeneratedSMSController extends Controller
{
    //
}
