 <div class="container-fluid dropdown  pd-t-3 pd-b-3 text-right">
            <button class="badge container-fluid tx-13 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <b>Quick Action</b>
            </button>
            <div class="dropdown-menu dropdown-menu-right shadow-lg tx-12">
                <li class="dropdown-item custom-model-btn" url="{{url('MasterAdmin/Finance/StudentCustomFee/'.$studentid.'/index')}}" model-title="Add Custom/Other Fee" model-class="modal-xl" model-title-info="Student Add Custom/Other Fee"><i class="fa fa-plus"></i> Add Custom/Other Fee</li>
                <li class="dropdown-item custom-model-btn" url="{{url('MasterAdmin/Finance/StudentConcession/'.$studentid.'/index')}}" model-title="Add Student Concession" model-class="modal-xl" model-title-info="Student Concession Type"><i class="fa fa-percent"></i> Add Student Regular Concession</li>
                <li class="dropdown-item custom-model-btn" url="{{url('MasterAdmin/Finance/StudentFeeHeadConcession/'.$studentid.'/'.request()->route('feeuptodate').'/'.request()->route('feepayid').'/index')}}" model-title="Create Fee Head Concession" model-class="modal-xl" model-title-info="Create Fee Head Concession"><i class="fa fa-percent"></i> Create Fee Head Concession</li>
                <li class="dropdown-item custom-model-btn" url="{{url('MasterAdmin/Finance/StudentFeeHeadAvoid/'.$studentid.'/'.request()->route('feeuptodate').'/'.request()->route('feepayid').'/index')}}" model-title="Fee Head Disable" model-class="modal-xl" model-title-info="Student Fee Head Disable"><i class="fa fa-ban"></i> Fee Head Disable</li>
                <li class="dropdown-item custom-model-btn" url="{{url('MasterAdmin/Finance/StudentFeeHeadInstalmentAvoid/'.$studentid.'/'.request()->route('feeuptodate').'/'.request()->route('feepayid').'/index')}}" model-title="Fee Head Instalment Disable" model-class="modal-xl" model-title-info="Student Fee Head Instalment Disable"><i class="fa fa-ban"></i> Fee Head Instalment Disable</li>
                <li class="dropdown-item custom-model-btn" url="{{url('MasterAdmin/Finance/StudentFeeHeadFineConcession/'.$studentid.'/'.request()->route('feeuptodate').'/'.request()->route('feepayid').'/index')}}" model-title="Fee Head Fine Concession" model-class="modal-xl" model-title-info="Student Fee Head Fine Concession"><i class="fa fa-percentage"></i> Fee Head Fine Concession</li>
                <li class="dropdown-item custom-model-btn" url="{{url('MasterAdmin/Finance/StudentAssignTransport/'.$studentid.'/index')}}" model-title="Student Assign Transport" model-class="modal-xl" model-title-info="Student Assign Transport"><i class="fa fa-bus"></i> Manage Transport</li>
                <li class="dropdown-item custom-model-btn" url="{{url('MasterAdmin/Finance/AddACLedger/'.$studentid.'/index')}}" model-title="Add Student A/C Ledger Number" model-class="modal-xl" model-title-info="Add Student A/C Ledger Number"><i class="fa fa-plus"></i> Add A/C Ledger Number</li>
                <li class="dropdown-item custom-model-btn" url="{{url('MasterAdmin/Finance/StudentFeeLedgerPreview?studentid='.$studentid.'&feemonthdate='.request()->route('feeuptodate').'')}}" model-title="Student Fee Ledger Report" model-class="modal-xl" model-title-info="Student Fee Ledger Report"><i class="fa fa-plus"></i> Student Fee Ledger Report</li>
            </div>
        </div>
